--- apps/desktop/desktop_native/core/Cargo.toml.orig	2026-08-10 20:48:17 UTC
+++ apps/desktop/desktop_native/core/Cargo.toml
@@ -45,7 +45,7 @@ zeroizing-alloc = { workspace = true }
 [target.'cfg(not(windows))'.dependencies]
 zeroizing-alloc = { workspace = true }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd = { workspace = true, features = ["background", "clipboard", "remote_desktop", "screencast"] }
 homedir = { workspace = true }
 libc = { workspace = true }
