minimumReleaseAge: 360
allowBuilds:
  bufferutil: true
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true
overrides:
  vite: 8.1.0
  node-gyp: 13.0.0
  xml2js: 0.6.2
  node-fetch: 3.3.2
  '@electron/universal': 3.0.4
  '@babel/runtime': 8.0.0
  '@xmldom/xmldom@<0.8.12': 0.8.13
patchedDependencies:
  vudio@2.1.1: patches/vudio@2.1.1.patch
  '@malept/flatpak-bundler@0.4.0': patches/@malept__flatpak-bundler@0.4.0.patch
  kuromoji@0.1.2: patches/kuromoji@0.1.2.patch
  electron-is@3.0.0: patches/electron-is@3.0.0.patch
  mdui@2.1.4: patches/mdui@2.1.4.patch
engineStrict: true
minimumReleaseAgeExclude:
  - vite@8.1.0
